import { Plugin, ResolvedConfig } from 'vite';
import { spawn } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import * as esbuild from 'esbuild';

const _dirname = dirname(fileURLToPath(import.meta.url));

export interface R1PluginOptions {
  rustSrc?: string; // Default: 'src-tauri'
  wasmOut?: string; // Default: 'public/wasm'
  swSrc?: string;   // Optional override for Service Worker source
  manualBoot?: boolean; // If true, disable automatic injection of r1-boot.js
}

export function r1Plugin(options: R1PluginOptions = {}): Plugin {
  const {
    rustSrc = 'src-tauri',
    wasmOut = 'public/wasm',
  } = options;

  let config: ResolvedConfig;

  const getWasmName = () => {
    const cargoPath = resolve(config?.root || process.cwd(), rustSrc, 'Cargo.toml');
    if (existsSync(cargoPath)) {
      const content = readFileSync(cargoPath, 'utf8');
      
      // Try to find [lib] name first
      const libMatch = content.match(/\[lib\][^]*?name\s*=\s*"([^"]+)"/);
      if (libMatch) return libMatch[1].replace(/-/g, '_');

      // Fallback to [package] name
      const pkgMatch = content.match(/\[package\][^]*?name\s*=\s*"([^"]+)"/);
      if (pkgMatch) return pkgMatch[1].replace(/-/g, '_');

      // Broad fallback
      const match = content.match(/name\s*=\s*"([^"]+)"/);
      if (match) return match[1].replace(/-/g, '_');
    }
    return 'app';
  };

  const virtualEnvId = '/r1/env.js';
  const resolvedVirtualEnvId = '\0' + virtualEnvId;

  return {
    name: 'vite-plugin-r1',
    enforce: 'pre',

    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },

    resolveId(id) {
      if (id === virtualEnvId) {
        return resolvedVirtualEnvId;
      }
      return null;
    },

    load(id) {
      if (id === resolvedVirtualEnvId) {
        // This virtual module provides standard WASI/C stubs that delegate to the R1 Kernel's WASI shim.
        // These are common imports generated by wasm-bindgen when compiling C code via the WASI SDK.
        return `
          const delegate = (name) => (...args) => {
            if (globalThis.__R1_WASI__ && globalThis.__R1_WASI__[name]) {
              return globalThis.__R1_WASI__[name](...args);
            }
            // Fallback for non-kernel environments or early boot
            console.warn(\`[R1 env] Call to unmapped function: \${name}\`);
            return 0; 
          };

          export const memory = new WebAssembly.Memory({ initial: 256 });
          export const table = new WebAssembly.Table({ initial: 0, element: 'anyfunc' });
          
          // Common WASI/C symbols
          export const fd_write = delegate('fd_write');
          export const fd_read = delegate('fd_read');
          export const fd_close = delegate('fd_close');
          export const fd_seek = delegate('fd_seek');
          export const fd_fdstat_get = delegate('fd_fdstat_get');
          export const fd_filestat_get = delegate('fd_filestat_get');
          export const path_open = delegate('path_open');
          export const clock_time_get = delegate('clock_time_get');
          export const random_get = delegate('random_get');
          export const proc_exit = delegate('proc_exit');
          export const environ_get = delegate('environ_get');
          export const environ_sizes_get = delegate('environ_sizes_get');
          export const args_get = delegate('args_get');
          export const args_sizes_get = delegate('args_sizes_get');
          export const sched_yield = delegate('sched_yield');
          export const poll_oneoff = delegate('poll_oneoff');
        `;
      }
      return null;
    },

    async buildStart() {
      const cargoPath = resolve(config.root, rustSrc, 'Cargo.toml');
      if (existsSync(cargoPath)) {
        console.log(`[R1] Found Rust source at ${rustSrc}. Building WASM...`);
        
        await new Promise<void>((resolvePromise, reject) => {
          const child = spawn('wasm-pack', [
            'build',
            rustSrc,
            '--target', 'web',
            '--out-dir', resolve(config.root, wasmOut)
          ], { stdio: 'inherit', shell: true });

          child.on('error', (err: any) => {
            if (err.code === 'ENOENT') {
              console.warn('[R1] wasm-pack not found. Please install it: https://rustwasm.github.io/wasm-pack/installer/');
              resolvePromise(); // Don't crash the build stage if wasm-pack is missing, just warn
            } else {
              reject(err);
            }
          });

          child.on('close', (code) => {
            if (code === 0) resolvePromise();
            else {
              console.warn(`[R1] wasm-pack failed with code ${code}. Skipping WASM build.`);
              resolvePromise(); // Warn but proceed
            }
          });
        });
      }
    },

    transform(code, id) {
      if (id.includes(wasmOut) && id.endsWith('.js')) {
        if (code.includes('from "env"')) {
           console.log(`[R1 Plugin] Patching "env" imports in ${id}`);
           const envUrl = `${virtualEnvId}`; // We keep it relative here as transform is for bundling
           return {
             code: code.replace(/from\s+(['"])env\1/g, `from $1${envUrl}$1`),
             map: null
           };
        }
      }

      if (!id.match(/\.(js|ts|jsx|tsx)$/)) return null;
      if (id.includes('node_modules')) return null;

      // Import map for Tauri API paths to R1 equivalents
      const importMap: Record<string, string> = {
        '@tauri-apps/api/core':         '@r1/apis/core',
        '@tauri-apps/api/tauri':        '@r1/apis/core',
        '@tauri-apps/api/fs':           '@r1/apis/fs',
        '@tauri-apps/api/path':         '@r1/apis/path',
        '@tauri-apps/api/event':        '@r1/apis/event',
        '@tauri-apps/api/window':       '@r1/apis/window',
        '@tauri-apps/api/dialog':       '@r1/apis/dialog',
        '@tauri-apps/api/clipboard':    '@r1/apis/clipboard',
        '@tauri-apps/api/notification': '@r1/apis/notification',
        '@tauri-apps/api/os':           '@r1/apis/os',
        '@tauri-apps/api/shell':        '@r1/apis/shell',
        '@tauri-apps/api/http':         '@r1/apis/http',
        '@tauri-apps/api/store':        '@r1/apis/store',
        '@tauri-apps/plugin-store':     '@r1/apis/store',
        '@tauri-apps/api':              '@r1/apis',
      };

      // Check if code contains any Tauri imports
      if (code.includes('@tauri-apps/api') || code.includes('@tauri-apps/plugin-store')) {
        let newCode = code;
        
        // Sort keys by length (longest first) to match sub-paths before bare imports
        const sortedKeys = Object.keys(importMap).sort((a, b) => b.length - a.length);
        
        for (const tauriPath of sortedKeys) {
          const r1Path = importMap[tauriPath];
          // Match both single and double quotes
          const regex = new RegExp(`(['"])${tauriPath.replace(/\//g, '\\/')}\\1`, 'g');
          newCode = newCode.replace(regex, `$1${r1Path}$1`);
        }
        
        return {
          code: newCode,
          map: null
        };
      }

      return null;
    },

    async transformIndexHtml(html: string) {
      if (options.manualBoot) return html;
      return {
        html,
        tags: [
          {
            tag: 'script',
            attrs: { type: 'module', src: '/r1-boot.js', id: 'r1-boot' },
            injectTo: 'head-prepend'
          }
        ]
      };
    },

    async generateBundle() {
      // 1. Bundle and emit the Service Worker
      const swEntry = options.swSrc || resolve(_dirname, '../../sw/src/index.ts');
      if (existsSync(swEntry)) {
        console.log(`[R1] Bundling Service Worker from ${swEntry}...`);
        const result = await esbuild.build({
          entryPoints: [swEntry],
          bundle: true,
          write: false,
          format: 'iife',
          minify: true,
          loader: { '.css': 'empty' },
        });

        this.emitFile({
          type: 'asset',
          fileName: 'r1-sw.js',
          source: result.outputFiles[0].text
        });
      }

      // 2. Bundle and emit the Kernel Worker (sw.js)
      const kernelEntry = resolve(_dirname, '../../kernel/src/kernel.worker.ts');
      if (existsSync(kernelEntry)) {
        console.log(`[R1] Bundling Kernel Worker from ${kernelEntry}...`);
        const result = await esbuild.build({
          entryPoints: [kernelEntry],
          bundle: true,
          write: false,
          format: 'iife',
          minify: true,
          loader: { '.css': 'empty' },
        });

        this.emitFile({
          type: 'asset',
          fileName: 'sw.js',
          source: result.outputFiles[0].text
        });
      }

      // 3. Bundle and emit the R1 Boot script (to avoid bare import errors)
      const wasmName = getWasmName();
      const bootScript = `
        import { R1Runtime } from '@r1/core';
        console.log('[R1] Booting Runtime...');
        const r1 = new R1Runtime();
        r1.boot({ 
          wasmPath: '/wasm/${wasmName}.js' 
        }).then(() => {
          console.log('[R1] Boot complete.');
          window.dispatchEvent(new Event('r1:ready'));
        });
      `;
      
      console.log('[R1] Bundling R1 Boot script...');
      const result = await esbuild.build({
        stdin: {
          contents: bootScript,
          resolveDir: process.cwd(),
          loader: 'ts'
        },
        bundle: true,
        write: false,
        format: 'esm',
        minify: true,
        loader: { '.css': 'empty' },
      });

      this.emitFile({
        type: 'asset',
        fileName: 'r1-boot.js',
        source: result.outputFiles[0].text
      });
    },

    configureServer(server) {
      // Use unshift to ensure R1 middleware is at the very top of the stack
      server.middlewares.stack.unshift({
        route: '',
        handle: (req: any, res: any, next: any) => {
          const url = req.url || '';
          const rawPathname = url.split('?')[0].split('#')[0];
          
          // Identify virtual files strictly but independently of base path prefixes
          const isR1 = rawPathname.endsWith('/r1-sw.js') || 
                       rawPathname.endsWith('/sw.js') || 
                       rawPathname.endsWith('/r1-boot.js') ||
                       rawPathname.endsWith(virtualEnvId) ||
                       (rawPathname.startsWith('/wasm/') && rawPathname.endsWith('.js'));

          if (!isR1) {
            return next();
          }

          // We are handling this request. Strictly DO NOT call next() after this point.
          (async () => {
            try {
              console.log(`[R1 Plugin] Intercepting: ${rawPathname}`);

              let content = '';
              if (rawPathname.endsWith('/r1-sw.js') || rawPathname.endsWith('/sw.js')) {
                const entry = rawPathname.endsWith('/r1-sw.js')
                  ? (options.swSrc || resolve(_dirname, '../../sw/src/index.ts'))
                  : resolve(_dirname, '../../kernel/src/kernel.worker.ts');

                if (!existsSync(entry)) {
                  console.warn(`[R1 Plugin] Source not found: ${entry}`);
                  res.statusCode = 404;
                  return res.end(`console.error("[R1 Plugin] Source not found for ${rawPathname}");`);
                }

                const result = await esbuild.build({
                  entryPoints: [entry],
                  bundle: true,
                  write: false,
                  format: 'iife',
                  target: 'es2020',
                  minify: false,
                  loader: { '.css': 'empty', '.wasm': 'binary' },
                  define: { 'process.env.NODE_ENV': '"development"' }
                });
                content = result.outputFiles[0].text;
              } else if (rawPathname.endsWith('/r1-boot.js')) {
                const wasmName = getWasmName();
                const bootScript = `
                  import { R1Runtime } from '@r1/core';
                  if (!window.__R1_BOOT_STATUS__) {
                    const r1 = new R1Runtime();
                    r1.boot({ 
                      wasmPath: '/wasm/${wasmName}.js' 
                    }).then(() => {
                      window.dispatchEvent(new Event('r1:ready'));
                    }).catch(err => {
                      console.error('[R1] Boot failed:', err);
                      window.dispatchEvent(new CustomEvent('r1:error', { detail: err.message }));
                    });
                  }
                `;

                const result = await esbuild.build({
                  stdin: {
                    contents: bootScript,
                    resolveDir: resolve(_dirname, '..'),
                    loader: 'ts'
                  },
                  bundle: true,
                  write: false,
                  format: 'esm',
                  target: 'es2020',
                  minify: false,
                  loader: { '.css': 'empty' },
                  define: { 'process.env.NODE_ENV': '"development"' }
                });
                content = result.outputFiles[0].text;
              } else if (rawPathname.endsWith(virtualEnvId)) {
                content = `
                  const delegate = (name) => (...args) => {
                    if (globalThis.__R1_WASI__ && globalThis.__R1_WASI__[name]) {
                      return globalThis.__R1_WASI__[name](...args);
                    }
                    console.warn(\`[R1 env] Call to unmapped function: \${name}\`);
                    return 0; 
                  };

                  export const memory = new WebAssembly.Memory({ initial: 256 });
                  export const table = new WebAssembly.Table({ initial: 0, element: 'anyfunc' });
                  
                  export const fd_write = delegate('fd_write');
                  export const fd_read = delegate('fd_read');
                  export const fd_close = delegate('fd_close');
                  export const fd_seek = delegate('fd_seek');
                  export const fd_fdstat_get = delegate('fd_fdstat_get');
                  export const fd_filestat_get = delegate('fd_filestat_get');
                  export const path_open = delegate('path_open');
                  export const clock_time_get = delegate('clock_time_get');
                  export const random_get = delegate('random_get');
                  export const proc_exit = delegate('proc_exit');
                  export const environ_get = delegate('environ_get');
                  export const environ_sizes_get = delegate('environ_sizes_get');
                  export const args_get = delegate('args_get');
                  export const args_sizes_get = delegate('args_sizes_get');
                  export const sched_yield = delegate('sched_yield');
                  export const poll_oneoff = delegate('poll_oneoff');
                `;
              } else if (rawPathname.startsWith('/wasm/') && rawPathname.endsWith('.js')) {
                // Patch static WASM glue code on the fly
                const filePath = resolve(config.root, wasmOut, rawPathname.replace('/wasm/', ''));
                if (existsSync(filePath)) {
                  let code = readFileSync(filePath, 'utf8');
                  if (code.includes('from "env"')) {
                    console.log(`[R1 Plugin] Middleware patching "env" in ${rawPathname}`);
                    const protocol = req.socket.remotePort === 443 ? 'https' : 'http'; // Simplistic but usually OK for dev
                    const origin = `${protocol}://${req.headers.host}`;
                    const envUrl = `${origin}${virtualEnvId}`;
                    code = code.replace(/from\s+(['"])env\1/g, `from $1${envUrl}$1`);
                  }
                  content = code;
                } else {
                  return next(); // Let Vite handle 404
                }
              }

              res.setHeader('Content-Type', 'application/javascript');
              res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
              if (rawPathname.endsWith('/r1-sw.js')) {
                res.setHeader('Service-Worker-Allowed', '/');
              }
              res.end(content);
            } catch (err) {
              console.error(`[R1 Plugin] Error serving ${rawPathname}:`, err);
              if (!res.headersSent) {
                res.statusCode = 500;
                res.setHeader('Content-Type', 'application/javascript');
                res.end(`console.error("[R1 Plugin] Failed to build ${rawPathname}: ${String(err).replace(/"/g, "'")}");`);
              }
            }
          })();
        }
      } as any);
    }
  };
}
