[env]
CC_wasm32_unknown_unknown = "C:\\LLVM\\bin\\clang.exe"
CFLAGS_wasm32_unknown_unknown = "--sysroot=C:\\wasi-sdk\\share\\wasi-sysroot -I C:\\wasi-sdk\\share\\wasi-sysroot\\include\\wasm32-wasi -DSQLITE_OS_OTHER=1"
